SYMBOLS = [
    "BTCUSDT",
    "ETHUSDT",
    "BCHUSDT",
    "XRPUSDT",
    "EOSUSDT",
    "LTCUSDT",
    "TRXUSDT",
    "ETCUSDT",
    "LINKUSDT",
    "XLMUSDT",
    "ADAUSDT",
    "XMRUSDT",
    "DASHUSDT",
    "ZECUSDT",
    "XTZUSDT",
    "BNBUSDT",
    "ATOMUSDT",
    "ONTUSDT",
    "IOTAUSDT",
    "BATUSDT",
    "VETUSDT",
    "NEOUSDT",
    "QTUMUSDT",
    "IOSTUSDT",
    "THETAUSDT",
    "ALGOUSDT",
    "ZILUSDT",
    "KNCUSDT",
    "ZRXUSDT",
    "COMPUSDT",
    "OMGUSDT",
    "DOGEUSDT",
    "SXPUSDT",
    "KAVAUSDT",
    "BANDUSDT",
    "RLCUSDT",
    "WAVESUSDT",
    "MKRUSDT",
    "SNXUSDT",
    "DOTUSDT",
    "DEFIUSDT",
    "YFIUSDT",
    "BALUSDT",
    "CRVUSDT",
    "TRBUSDT",
    "RUNEUSDT",
    "SUSHIUSDT",
    "SRMUSDT",
    "EGLDUSDT",
    "SOLUSDT",
    "ICXUSDT",
    "STORJUSDT",
    "BLZUSDT",
    "UNIUSDT",
    "AVAXUSDT",
    "FTMUSDT",
    "HNTUSDT",
    "ENJUSDT",
    "FLMUSDT",
    "TOMOUSDT",
    "RENUSDT",
    "KSMUSDT",
    "NEARUSDT",
    "AAVEUSDT",
    "FILUSDT",
    "RSRUSDT",
    "LRCUSDT",
    "MATICUSDT",
    "OCEANUSDT",
    "CVCUSDT",
    "BELUSDT",
    "CTKUSDT",
    "AXSUSDT",
    "ALPHAUSDT",
    "ZENUSDT",
    "SKLUSDT",
    "GRTUSDT",
    "1INCHUSDT",
    "CHZUSDT",
    "SANDUSDT",
    "ANKRUSDT",
    "BTSUSDT",
    "LITUSDT",
    "UNFIUSDT",
    "REEFUSDT",
    "RVNUSDT",
    "SFPUSDT",
    "XEMUSDT",
    "BTCSTUSDT",
    "COTIUSDT",
    "CHRUSDT",
    "MANAUSDT",
    "ALICEUSDT",
    "HBARUSDT",
    "ONEUSDT",
    "LINAUSDT",
    "STMXUSDT",
    "DENTUSDT",
    "CELRUSDT",
    "HOTUSDT",
    "MTLUSDT",
    "OGNUSDT",
    "NKNUSDT",
    "SCUSDT",
    "DGBUSDT",
    "1000SHIBUSDT",
    "BAKEUSDT",
    "GTCUSDT",
    "BTCDOMUSDT",
    "IOTXUSDT",
    "AUDIOUSDT",
    "RAYUSDT",
    "C98USDT",
    "MASKUSDT",
    "ATAUSDT",
    "DYDXUSDT",
    "1000XECUSDT",
    "GALAUSDT",
    "CELOUSDT",
    "ARUSDT",
    "KLAYUSDT",
    "ARPAUSDT",
    "CTSIUSDT",
    "LPTUSDT",
    "ENSUSDT",
    "PEOPLEUSDT",
    "ANTUSDT",
    "ROSEUSDT",
    "DUSKUSDT",
    "FLOWUSDT",
    "IMXUSDT",
    "API3USDT",
    "GMTUSDT",
    "APEUSDT",
    "WOOUSDT",
    "FTTUSDT",
    "JASMYUSDT",
    "DARUSDT",
    "GALUSDT",
    "OPUSDT",
    "INJUSDT",
    "STGUSDT",
    "SPELLUSDT",
    "1000LUNCUSDT",
    "LUNA2USDT",
    "LDOUSDT",
    "CVXUSDT",
    "ICPUSDT",
    "APTUSDT",
    "QNTUSDT",
    "BLUEBIRDUSDT",
    "FETUSDT",
    "FXSUSDT",
    "HOOKUSDT",
    "MAGICUSDT",
    "TUSDT",
    "RNDRUSDT",
    "HIGHUSDT",
    "MINAUSDT",
    "ASTRUSDT",
    "AGIXUSDT",
    "PHBUSDT",
    "GMXUSDT",
    "CFXUSDT",
    "STXUSDT",
    "COCOSUSDT",
    "BNXUSDT",
    "ACHUSDT",
    "SSVUSDT",
    "CKBUSDT",
    "PERPUSDT",
    "TRUUSDT",
    "LQTYUSDT",
    "USDCUSDT",
    "IDUSDT",
    "ARBUSDT",
    "JOEUSDT",
    "TLMUSDT",
    "AMBUSDT",
    "LEVERUSDT",
    "RDNTUSDT",
    "HFTUSDT",
    "XVSUSDT",
    "BLURUSDT",
    "EDUUSDT",
    "IDEXUSDT",
    "SUIUSDT",
    "1000PEPEUSDT",
    "1000FLOKIUSDT",
    "UMAUSDT",
    "RADUSDT",
    "KEYUSDT",
    "COMBOUSDT",
    "NMRUSDT",
    "MDTUSDT",
    "XVGUSDT",
    "WLDUSDT",
    "PENDLEUSDT",
    "ARKMUSDT",
    "AGLDUSDT",
    "YGGUSDT",
    "DODOXUSDT",
];

SYMBOL_PRECISION = {
    "BTCUSDT" : 3,
    "ETHUSDT" : 3,
    "BCHUSDT" : 3,
    "XRPUSDT" : 1,
    "EOSUSDT" : 1,
    "LTCUSDT" : 3,
    "TRXUSDT" : 0,
    "ETCUSDT" : 2,
    "LINKUSDT" : 2,
    "XLMUSDT" : 0,
    "ADAUSDT" : 0,
    "XMRUSDT" : 3,
    "DASHUSDT" : 3,
    "ZECUSDT" : 3,
    "XTZUSDT" : 1,
    "BNBUSDT" : 2,
    "ATOMUSDT" : 2,
    "ONTUSDT" : 1,
    "IOTAUSDT" : 1,
    "BATUSDT" : 1,
    "VETUSDT" : 0,
    "NEOUSDT" : 2,
    "QTUMUSDT" : 1,
    "IOSTUSDT" : 0,
    "THETAUSDT" : 1,
    "ALGOUSDT" : 1,
    "ZILUSDT" : 0,
    "KNCUSDT" : 0,
    "ZRXUSDT" : 1,
    "COMPUSDT" : 3,
    "OMGUSDT" : 1,
    "DOGEUSDT" : 0,
    "SXPUSDT" : 1,
    "KAVAUSDT" : 1,
    "BANDUSDT" : 1,
    "RLCUSDT" : 1,
    "WAVESUSDT" : 1,
    "MKRUSDT" : 3,
    "SNXUSDT" : 1,
    "DOTUSDT" : 1,
    "DEFIUSDT" : 3,
    "YFIUSDT" : 3,
    "BALUSDT" : 1,
    "CRVUSDT" : 1,
    "TRBUSDT" : 1,
    "RUNEUSDT" : 0,
    "SUSHIUSDT" : 0,
    "SRMUSDT" : 0,
    "EGLDUSDT" : 1,
    "SOLUSDT" : 0,
    "ICXUSDT" : 0,
    "STORJUSDT" : 0,
    "BLZUSDT" : 0,
    "UNIUSDT" : 0,
    "AVAXUSDT" : 0,
    "FTMUSDT" : 0,
    "HNTUSDT" : 0,
    "ENJUSDT" : 0,
    "FLMUSDT" : 0,
    "TOMOUSDT" : 0,
    "RENUSDT" : 0,
    "KSMUSDT" : 1,
    "NEARUSDT" : 0,
    "AAVEUSDT" : 1,
    "FILUSDT" : 1,
    "RSRUSDT" : 0,
    "LRCUSDT" : 0,
    "MATICUSDT" : 0,
    "OCEANUSDT" : 0,
    "CVCUSDT" : 0,
    "BELUSDT" : 0,
    "CTKUSDT" : 0,
    "AXSUSDT" : 0,
    "ALPHAUSDT" : 0,
    "ZENUSDT" : 1,
    "SKLUSDT" : 0,
    "GRTUSDT" : 0,
    "1INCHUSDT" : 0,
    "BTCBUSD" : 3,
    "CHZUSDT" : 0,
    "SANDUSDT" : 0,
    "ANKRUSDT" : 0,
    "BTSUSDT" : 0,
    "LITUSDT" : 1,
    "UNFIUSDT" : 1,
    "REEFUSDT" : 0,
    "RVNUSDT" : 0,
    "SFPUSDT" : 0,
    "XEMUSDT" : 0,
    "BTCSTUSDT" : 1,
    "COTIUSDT" : 0,
    "CHRUSDT" : 0,
    "MANAUSDT" : 0,
    "ALICEUSDT" : 1,
    "HBARUSDT" : 0,
    "ONEUSDT" : 0,
    "LINAUSDT" : 0,
    "STMXUSDT" : 0,
    "DENTUSDT" : 0,
    "CELRUSDT" : 0,
    "HOTUSDT" : 0,
    "MTLUSDT" : 0,
    "OGNUSDT" : 0,
    "NKNUSDT" : 0,
    "SCUSDT" : 0,
    "DGBUSDT" : 0,
    "1000SHIBUSDT" : 0,
    "BAKEUSDT" : 0,
    "GTCUSDT" : 1,
    "ETHBUSD" : 3,
    "BTCDOMUSDT" : 3,
    "BNBBUSD" : 2,
    "ADABUSD" : 0,
    "XRPBUSD" : 1,
    "IOTXUSDT" : 0,
    "DOGEBUSD" : 0,
    "AUDIOUSDT" : 0,
    "RAYUSDT" : 1,
    "C98USDT" : 0,
    "MASKUSDT" : 0,
    "ATAUSDT" : 0,
    "SOLBUSD" : 0,
    "FTTBUSD" : 1,
    "DYDXUSDT" : 1,
    "1000XECUSDT" : 0,
    "GALAUSDT" : 0,
    "CELOUSDT" : 1,
    "ARUSDT" : 1,
    "KLAYUSDT" : 1,
    "ARPAUSDT" : 0,
    "CTSIUSDT" : 0,
    "LPTUSDT" : 1,
    "ENSUSDT" : 1,
    "PEOPLEUSDT" : 0,
    "ANTUSDT" : 1,
    "ROSEUSDT" : 0,
    "DUSKUSDT" : 0,
    "FLOWUSDT" : 1,
    "IMXUSDT" : 0,
    "API3USDT" : 1,
    "GMTUSDT" : 0,
    "APEUSDT" : 0,
    "WOOUSDT" : 0,
    "FTTUSDT" : 1,
    "JASMYUSDT" : 0,
    "DARUSDT" : 1,
    "GALUSDT" : 0,
    "AVAXBUSD" : 1,
    "NEARBUSD" : 1,
    "GMTBUSD" : 1,
    "APEBUSD" : 1,
    "GALBUSD" : 0,
    "FTMBUSD" : 0,
    "DODOBUSD" : 0,
    "ANCBUSD" : 0,
    "GALABUSD" : 0,
    "TRXBUSD" : 0,
    "1000LUNCBUSD" : 0,
    "OPUSDT" : 1,
    "DOTBUSD" : 1,
    "TLMBUSD" : 0,
    "WAVESBUSD" : 1,
    "LINKBUSD" : 1,
    "SANDBUSD" : 1,
    "LTCBUSD" : 2,
    "MATICBUSD" : 0,
    "CVXBUSD" : 1,
    "FILBUSD" : 1,
    "1000SHIBBUSD" : 0,
    "LEVERBUSD" : 0,
    "ETCBUSD" : 1,
    "LDOBUSD" : 1,
    "UNIBUSD" : 1,
    "AUCTIONBUSD" : 1,
    "INJUSDT" : 1,
    "STGUSDT" : 0,
    "SPELLUSDT" : 0,
    "1000LUNCUSDT" : 0,
    "LUNA2USDT" : 0,
    "AMBBUSD" : 0,
    "PHBBUSD" : 0,
    "LDOUSDT" : 0,
    "CVXUSDT" : 0,
    "ICPUSDT" : 0,
    "APTUSDT" : 1,
    "QNTUSDT" : 1,
    "APTBUSD" : 1,
    "BLUEBIRDUSDT" : 1,
    "FETUSDT" : 0,
    "AGIXBUSD" : 0,
    "FXSUSDT" : 1,
    "HOOKUSDT" : 1,
    "MAGICUSDT" : 1,
    "TUSDT" : 0,
    "RNDRUSDT" : 1,
    "HIGHUSDT" : 1,
    "MINAUSDT" : 0,
    "ASTRUSDT" : 0,
    "AGIXUSDT" : 0,
    "PHBUSDT" : 0,
    "GMXUSDT" : 2,
    "CFXUSDT" : 0,
    "STXUSDT" : 0,
    "COCOSUSDT" : 1,
    "BNXUSDT" : 1,
    "ACHUSDT" : 0,
    "SSVUSDT" : 2,
    "CKBUSDT" : 0,
    "PERPUSDT" : 1,
    "TRUUSDT" : 0,
    "LQTYUSDT" : 1,
    "USDCUSDT" : 0,
    "IDUSDT" : 0,
    "ARBUSDT" : 1,
    "JOEUSDT" : 0,
    "TLMUSDT" : 0,
    "AMBUSDT" : 0,
    "LEVERUSDT" : 0,
    "RDNTUSDT" : 0,
    "HFTUSDT" : 0,
    "XVSUSDT" : 1,
    "ETHBTC" : 2,
    "BLURUSDT" : 0,
    "EDUUSDT" : 0,
    "IDEXUSDT" : 0,
    "SUIUSDT" : 1,
    "1000PEPEUSDT" : 0,
    "1000FLOKIUSDT" : 0,
    "UMAUSDT" : 0,
    "RADUSDT" : 0,
    "KEYUSDT" : 0,
    "COMBOUSDT" : 1,
    "NMRUSDT" : 1,
    "MDTUSDT" : 0,
    "XVGUSDT" : 0,
    "WLDUSDT" : 0,
    "PENDLEUSDT" : 0,
    "ARKMUSDT" : 0,
    "AGLDUSDT" : 0,
    "YGGUSDT" : 0,
    "DODOXUSDT" : 0
}; 
SYMBOL_PRICE_PRECISION = {
    "BTCUSDT" : 1,
    "ETHUSDT" : 2,
    "BCHUSDT" : 2,
    "XRPUSDT" : 4,
    "EOSUSDT" : 3,
    "LTCUSDT" : 2,
    "TRXUSDT" : 5,
    "ETCUSDT" : 3,
    "LINKUSDT" : 3,
    "XLMUSDT" : 5,
    "ADAUSDT" : 4,
    "XMRUSDT" : 2,
    "DASHUSDT" : 2,
    "ZECUSDT" : 2,
    "XTZUSDT" : 3,
    "BNBUSDT" : 2,
    "ATOMUSDT" : 3,
    "ONTUSDT" : 4,
    "IOTAUSDT" : 4,
    "BATUSDT" : 4,
    "VETUSDT" : 5,
    "NEOUSDT" : 3,
    "QTUMUSDT" : 3,
    "IOSTUSDT" : 6,
    "THETAUSDT" : 4,
    "ALGOUSDT" : 4,
    "ZILUSDT" : 5,
    "KNCUSDT" : 4,
    "ZRXUSDT" : 4,
    "COMPUSDT" : 2,
    "OMGUSDT" : 4,
    "DOGEUSDT" : 5,
    "SXPUSDT" : 4,
    "KAVAUSDT" : 4,
    "BANDUSDT" : 4,
    "RLCUSDT" : 4,
    "WAVESUSDT" : 4,
    "MKRUSDT" : 1,
    "SNXUSDT" : 3,
    "DOTUSDT" : 3,
    "DEFIUSDT" : 1,
    "YFIUSDT" : 0,
    "BALUSDT" : 3,
    "CRVUSDT" : 3,
    "TRBUSDT" : 3,
    "RUNEUSDT" : 3,
    "SUSHIUSDT" : 4,
    "SRMUSDT" : 4,
    "EGLDUSDT" : 2,
    "SOLUSDT" : 3,
    "ICXUSDT" : 4,
    "STORJUSDT" : 4,
    "BLZUSDT" : 5,
    "UNIUSDT" : 3,
    "AVAXUSDT" : 3,
    "FTMUSDT" : 4,
    "HNTUSDT" : 3,
    "ENJUSDT" : 4,
    "FLMUSDT" : 4,
    "TOMOUSDT" : 4,
    "RENUSDT" : 5,
    "KSMUSDT" : 2,
    "NEARUSDT" : 3,
    "AAVEUSDT" : 2,
    "FILUSDT" : 3,
    "RSRUSDT" : 6,
    "LRCUSDT" : 4,
    "MATICUSDT" : 4,
    "OCEANUSDT" : 4,
    "CVCUSDT" : 5,
    "BELUSDT" : 4,
    "CTKUSDT" : 4,
    "AXSUSDT" : 3,
    "ALPHAUSDT" : 5,
    "ZENUSDT" : 3,
    "SKLUSDT" : 5,
    "GRTUSDT" : 5,
    "1INCHUSDT" : 4,
    "CHZUSDT" : 5,
    "SANDUSDT" : 4,
    "ANKRUSDT" : 5,
    "BTSUSDT" : 5,
    "LITUSDT" : 3,
    "UNFIUSDT" : 3,
    "REEFUSDT" : 6,
    "RVNUSDT" : 5,
    "SFPUSDT" : 4,
    "XEMUSDT" : 4,
    "BTCSTUSDT" : 3,
    "COTIUSDT" : 5,
    "CHRUSDT" : 4,
    "MANAUSDT" : 4,
    "ALICEUSDT" : 3,
    "HBARUSDT" : 5,
    "ONEUSDT" : 5,
    "LINAUSDT" : 5,
    "STMXUSDT" : 5,
    "DENTUSDT" : 6,
    "CELRUSDT" : 5,
    "HOTUSDT" : 6,
    "MTLUSDT" : 4,
    "OGNUSDT" : 4,
    "NKNUSDT" : 5,
    "SCUSDT" : 6,
    "DGBUSDT" : 5,
    "1000SHIBUSDT" : 6,
    "BAKEUSDT" : 4,
    "GTCUSDT" : 3,
    "BTCDOMUSDT" : 1,
    "IOTXUSDT" : 5,
    "AUDIOUSDT" : 4,
    "RAYUSDT" : 3,
    "C98USDT" : 4,
    "MASKUSDT" : 3,
    "ATAUSDT" : 4,
    "DYDXUSDT" : 3,
    "1000XECUSDT" : 5,
    "GALAUSDT" : 5,
    "CELOUSDT" : 3,
    "ARUSDT" : 3,
    "KLAYUSDT" : 4,
    "ARPAUSDT" : 5,
    "CTSIUSDT" : 4,
    "LPTUSDT" : 3,
    "ENSUSDT" : 3,
    "PEOPLEUSDT" : 5,
    "ANTUSDT" : 3,
    "ROSEUSDT" : 5,
    "DUSKUSDT" : 5,
    "FLOWUSDT" : 3,
    "IMXUSDT" : 4,
    "API3USDT" : 4,
    "GMTUSDT" : 4,
    "APEUSDT" : 3,
    "WOOUSDT" : 5,
    "FTTUSDT" : 4,
    "JASMYUSDT" : 6,
    "DARUSDT" : 4,
    "GALUSDT" : 4,
    "OPUSDT" : 4,
    "INJUSDT" : 3,
    "STGUSDT" : 4,
    "FOOTBALLUSDT" : 2,
    "SPELLUSDT" : 7,
    "1000LUNCUSDT" : 5,
    "LUNA2USDT" : 4,
    "LDOUSDT" : 4,
    "CVXUSDT" : 3,
    "ICPUSDT" : 3,
    "APTUSDT" : 3,
    "QNTUSDT" : 2,
    "BLUEBIRDUSDT" : 3,
    "FETUSDT" : 4,
    "FXSUSDT" : 3,
    "HOOKUSDT" : 4,
    "MAGICUSDT" : 4,
    "TUSDT" : 5,
    "RNDRUSDT" : 4,
    "HIGHUSDT" : 3,
    "MINAUSDT" : 4,
    "ASTRUSDT" : 5,
    "AGIXUSDT" : 4,
    "PHBUSDT" : 4,
    "GMXUSDT" : 2,
    "CFXUSDT" : 4,
    "STXUSDT" : 4,
    "COCOSUSDT" : 3,
    "BNXUSDT" : 4,
    "ACHUSDT" : 5,
    "SSVUSDT" : 2,
    "CKBUSDT" : 6,
    "PERPUSDT" : 4,
    "TRUUSDT" : 5,
    "LQTYUSDT" : 4,
    "USDCUSDT" : 5,
    "IDUSDT" : 4,
    "ARBUSDT" : 4,
    "JOEUSDT" : 4,
    "TLMUSDT" : 5,
    "AMBUSDT" : 6,
    "LEVERUSDT" : 6,
    "RDNTUSDT" : 4,
    "HFTUSDT" : 4,
    "XVSUSDT" : 3,
    "BLURUSDT" : 4,
    "EDUUSDT" : 4,
    "IDEXUSDT" : 5,
    "SUIUSDT" : 4,
    "1000PEPEUSDT" : 7,
    "1000FLOKIUSDT" : 5,
    "UMAUSDT" : 3,
    "RADUSDT" : 3,
    "KEYUSDT" : 6,
    "COMBOUSDT" : 4,
    "NMRUSDT" : 2,
    "MAVUSDT" : 4,
    "MDTUSDT" : 5,
    "XVGUSDT" : 6,
    "WLDUSDT" : 4,
    "PENDLEUSDT" : 4,
    "ARKMUSDT" : 4,
    "AGLDUSDT" : 4,
    "YGGUSDT" : 4,
    "DODOXUSDT" : 5,
    "BNTUSDT" : 4,
    "OXTUSDT" : 5,
    "SEIUSDT" : 4,
    "CYBERUSDT" : 3,
    "HIFIUSDT" : 4,
    "ARKUSDT" : 4,
    "FRONTUSDT" : 4,
    "GLMRUSDT" : 4,
    "BICOUSDT" : 4,
    "STRAXUSDT" : 4,
    "LOOMUSDT" : 4,
    "BIGTIMEUSDT" : 4,
};



for s in SYMBOLS:

    print(f'"{s}" =>  SymbolInfo £ quantity_precision: {SYMBOL_PRECISION[s]}, price_precision: {SYMBOL_PRICE_PRECISION[s]} $,')
